name: "Project Error Release"
description: "Auto release for Project Error projects"
inputs:
  title:
    description: "The title for the release"
    required: false
  prerelease:
    description: "If the release is a pre release"
    required: false
  automatic_release_tag:
    description: "Automatic release tag. Will delete the old."
    required: false
  environment:
    description: "The environment for the release"
    required: false
  files:
    description: "Files to upload"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
