name: "WSS Release"
description: "Auto release for WSS projects"
inputs:
  repo_token:
    description: "GitHub secret token"
    required: true
  title:
    description: "The title for the release"
    required: false
  prerelease:
    description: "If the release is a pre release"
    required: false
  automatic_release_tag:
    description: "Automatic release tag. Will delete the old."
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
